version: 0.2
phases:
  pre_build:
    commands:
      - cd infradeployment
      - terraform fmt
      - terraform init
      - terraform validate
      - terraform workspace select PRD
  
  build:
    commands:
      - terraform apply -no-color -auto-approve -var-file=./env/PRD.tfvars